### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by nouryehia** [rafegers0n/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
   - All `ssh` examples should be in backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
   - steps should be headers
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
   - keystroked not counted
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by gman-ui** [comment]
The instructions only asked us to post screenshots, and the things that I was marked off for were not really called out in the instructions. For going forward, how am I supposed to account for things not called out in the instructions?

**Comment by nouryehia** [comment]
Going forward, just make sure to follow the same conventions when making Markdown files. Most of these are formatting as you can see.
